server:
  port: 9111
  context-path: /fd
    #ssl配置
bloodSugger:
  fasting: 00:00-07:59
  afterBreakfast: 08:00-09:59
  beforeLunch: 10:00-11:59
  afterLunch: 12:00-13:59
  beforeDinner: 14:00-17:59
  afterDinner: 18:00-19:59
  beforeSleep: 20:00-23:59

yihu:
  gateway:
    url: http://service.yihu.com:8080/WSGW/rest
    client:
      id: 9000237
      version: 1.0
  xiaowei:
    comunity: http://xwsqtest.yihu.com/tags.aspx
    wechat: MyFamilyDoctors

neusoft:
  ws:
    doctor: http://219.139.130.106:8884/phis_hubei_ws/ws/doctorWsService?wsdl
    person: http://219.139.130.106:8884/phis_hubei_ws/ws/personWsService?wsdl
    key: JKZL

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password:
#    driverClassName: com.mysql.jdbc.Driver
    maxTotal: 500
    maxIdle: 30
system:
  profile: /system.yichang.properties
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://172.19.103.77:3306/yichang?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
    maxTotal: 500
    maxIdle: 30
system:
  profile: /system.test.properties


---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://10.27.8.70:3306/familydoctor?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: fd
    password: fd
#    driverClassName: com.mysql.jdbc.Driver
    maxTotal: 500
    maxIdle: 30
system:
  profile: /system.prod.properties
server:
  port: 8883
  context-path: /fd

---
spring:
  profiles: lfq
  datasource:
    url: jdbc:mysql://172.19.103.77:3306/yichang?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
    maxTotal: 500
    maxIdle: 30
bloodSugger:
  fasting: 00:00-07:59
  afterBreakfast: 08:00-09:59
  beforeLunch: 10:00-11:59
  afterLunch: 12:00-13:59
  beforeDinner: 14:00-17:59
  afterDinner: 18:00-19:59
  beforeSleep: 20:00-23:59

#server:
#  port: 9113
#  context-path: /fd

yihu:
  gateway:
    url: http://service.yihu.com:8080/WSGW/rest
    client:
      id: 9000237
      version: 1.0
system:
  profile: /system.yichang.properties

