server:
  port: 8080
  context-path: /fd
    #ssl配置
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.19.103.77:3306/yichang?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
    maxTotal: 500
    maxIdle: 30
